### ISSUE TITLE
Add Browsing Features for Dates (Add Date Facet) (User Story #16)

### ISSUE THREAD

**Issue by gordonleacock** [mlibrary/fishrappr#11]
Description: 
a User can browse Daily pages by Dates using Decade, Calendar Year, Month, or Day

Acceptance Criteria:

- [ ] I can find pages by various data units.
- [ ] Date facets are visible and clear

**Comment by njaffer** [comment]
@gordonleacock: Can we close this one, same/related to #12

**Comment by kaylaondracek** [comment]
Per the refinement meeting 4/26, it seems like we all felt that additional filters beyond date range (like the decade facet) were redundant. I think we can close it!

**Comment by gordonleacock** [comment]
Closing as redundant.

**Comment by gordonleacock** [comment]
Okay, I just closed it.
