### ISSUE TITLE
Toggle hit highlighting off of page image

### ISSUE THREAD

**Issue by kaylaondracek** [mlibrary/fishrappr#114]
## Description: 
As a user, I want to have the ability to remove hit highlighting when reviewing image in image viewer so that I can read the page without distraction

## Acceptance Criteria:

- [x] 1. User is able to toggle hit highlighting off when viewing a page in the page viewer from search results screen

**Comment by respinos** [comment]
Initial implementation: 

- "Show/Hide Hit Highlights" is visible only when the particular page has highlighted text (e.g. follow a search result link, then page through the rest of the issue to pages that were not part of the search results)
- toggle is a remembered setting: if you toggle highlights off, the next page with highlights will also have highlights off
