### ISSUE TITLE
Investigate date range graph options

### ISSUE THREAD

**Issue by kaylaondracek** [mlibrary/fishrappr#115]
## Description: 
As a user, I want to be able to view a graphical indication of date coverage for my search results so that I can have a sense of how often my search terms were used in this content throughout time.

This is a research track story. Investigating more robust implementation of date graph. For example of feature target, see ProQuest's date range slider & graph.

## Acceptance Criteria:
- [x] 1. Investigate displaying # of records per bar on hover rather than label on x-axis. Does this present issues for accessibility? Is a graph an accessible feature in the first place?
- [x] 2. Investigate decade level graph
- [x] 3. Year-level graph
- [x] 4. Month-level graph
- [x] 5. Day-level graph

**Comment by kaylaondracek** [comment]
@gordonleacock - would you say you're largely done with investigation on the date graph and are moving into implementation? i just noticed we didn't actually close this out.

**Comment by gordonleacock** [comment]
Yes and now the implementation is close to done.
