### ISSUE TITLE
Filter Search by Date Facet (User Story 16A)

### ISSUE THREAD

**Issue by gordonleacock** [mlibrary/fishrappr#12]
Description: 
Once a User has search results, s/he can filter them using date facets

Acceptance Criteria:

- [x] I can limit search results using various date units and thus see what students wrote about a specific event (time) in history.
- [x] I can easily browse and use date filter tools to narrow search results for a specific decade, month or day.

**Comment by njaffer** [comment]
'Date units' as 'within 5,10, 15 years'?

**Comment by gordonleacock** [comment]
This was my trying to interpret how we could enable someone to focus on the
materials related some historic event.

So, select one week or month or (less likely) year before and after some
significant date.
