### ISSUE TITLE
Hit highlighting on OCR search results is not working as expected

### ISSUE THREAD

**Issue by kaylaondracek** [mlibrary/fishrappr#122]
## Description: 
Hit highlighting on OCR is not working as expected.

**Steps to reproduce - search results scenario**
- Navigate to fishrappr testing site: fishrappr-bhl-staging.hydra.lib.umich.edu
- Search for ROTC from the home page search (bug can be reproduced in "The Daily Standup" and in "Michigan Daily"
- Default search results view is list view.
- Observe no hit highlighting on results snippets
- User may observe highlights briefly appearing and then disappearing on load

**Steps to reproduce - extended full text scenario**

- From last step of first scenario, select _December 10, 1969   Issue 80   Image 1_  result to view full page OCR & Page image in viewer
- Select "View Plain Text" if this is not default landing
- Observe highlighting extends past ROTC keyword
- Note that this does not happen with every result! Observe December 10, 1969   Issue 80   Image 4  full page OCR has properly-functioning  hit highlighting (although not on list results snippet)

Main issue is first scenario. Second scenario is rare as far as I can tell.

**Expected behavior:**
Keywords are highlighted in OCR text in both the list view of search results. Highlighting extends from the beginning of the hit keyword/phrase to the end of the keyword/phrase.

**Actual behavior:**
Keywords are not highlighted in OCR text in list view of search results (or are being removed).

Screenshots
Hit highlighting not appearing in search results list view:
![screen shot 2016-06-22 at 12 35 43 pm](https://cloud.githubusercontent.com/assets/14596911/16274951/e0501330-3875-11e6-915c-d504b863eac4.png)

Full page OCR scenario:
![screen shot 2016-06-22 at 12 06 53 pm](https://cloud.githubusercontent.com/assets/14596911/16274954/e3fe3a3e-3875-11e6-9e12-071011bbde3c.png)

**Comment by respinos** [comment]
The problem with the highlights not appearing in search results is an artifact in the highlighting-toggle-javascript taking affect on the results pages.

The other problem will require changing how we configure solr highlighting --- the OCR has the characters `estoraIt<ion`, which would normally be escaped, but highlighting inserts HTML tags into the text (`<span>..</span>`) which require us to mark the fragment as "html safe". Clearly, it's not.
