### ISSUE TITLE
Select number of search results to display (User Story #24)

### ISSUE THREAD

**Issue by gordonleacock** [mlibrary/fishrappr#13]
Description: 
A User can select the number of search results to display per page (10, 20, 50, 100)

Acceptance Criteria:

- [x] I can adjust to see more results in one page.

**Comment by njaffer** [comment]
@gordonleacock, @kaylaondracek : Not sure if the second AC is relevant here? Is it implied when the user selects number of search results for a page?

**Comment by gordonleacock** [comment]
Removed the second AC (was "Implies pagination")

**Comment by kaylaondracek** [comment]
@njaffer Given UX's changes (removing the drop down, default number of results 100/page) & Mike's approval, should we close this story as it is no longer needed?
