### ISSUE TITLE
Improve UX & accessibility of navigation links

### ISSUE THREAD

**Issue by bnhowell** [mlibrary/fishrappr#132]
## Description: 

As a user I want to quickly and easily identify and navigate between the pages on the Fishrappr site by using the main navigation and footer navigation.

## Acceptance Criteria:

- [x] 1. Make main navigation link text color white and enlarge text size (18pt)
- [x] 2. In footer navigation: Style ‘Help’ lInk with a white button outline, white text and dark background. To the right of help will be the ‘Home’ (white text no white outline) linking to the home page. (see image below)

![screen shot 2016-07-01 at 11 32 04 am](https://cloud.githubusercontent.com/assets/16804543/16526815/199ce67e-3f81-11e6-9c6c-085df7ba9b15.png)

**Comment by gordonleacock** [comment]
I think this one is done.
