### ISSUE TITLE
Improve UX & accessibility of Search Results Page

### ISSUE THREAD

**Issue by bnhowell** [mlibrary/fishrappr#133]
## Description: 

As a user I want to quickly browse search results, navigate between search results pages, start a new search so I can find the article(s) that match my research needs. 

## Acceptance Criteria:

- [x] 1. Move ‘start over’ link text to the left side under the “You searched for: … “ text
- [x] 2. Make ‘start over’ link text size the same as normal paragraph size in the site and style with a text color (currently a blue) & contrast that meets WCAG AA standards
- [x] 3. Include button label text ‘previous page’ and ‘next page’ on the inside of the arrows of the search result page controls. (No ‘previous page’ button on first page of results and no ‘next page’ button on the last page of results)
- [x] 4. Reduce the size of buttons, text size in buttons and page results to the size of the ‘Sort by latest date’ dropdown’s text size in the same content section
- [x] 5. ‘Sort by’ dropdown can be on the same line as the search results
- [x] 6. Start and finish each search result snippet with an ellipses (...The text within the snippet…)
- [x] 7. Stop search results snippet paragraphs text from wrapping under the thumbnail
- [x] 8. Clearly identify the hit highlighting for search terms within the search snippet
- [x] 9. Insert a sticky ‘back to top’ button on the lower right hand side of the page when users scroll down long lists of search results (see below)

![screen shot 2016-07-01 at 1 51 38 pm](https://cloud.githubusercontent.com/assets/16804543/16530008/d7cf33a6-3f93-11e6-8f02-b8f0adf8435f.png)
- [x] 10. Place footer (the same as home page) in search results page

**Comment by gordonleacock** [comment]
Still working on ac 7 but I think ac 8 is done.

**Comment by gordonleacock** [comment]
This is now done. Per Roger we aren't using the supplied "Back to top" image - let's discuss at stand up next week.
