### ISSUE TITLE
Page Viewer UX and accessibility improvements

### ISSUE THREAD

**Issue by bnhowell** [mlibrary/fishrappr#134]
## Description: 

As a user I want to examine, zoom in/out on a full page view of the newspaper pages, read plain text, and download either plain text, image, pdf or the full issue.

## Acceptance Criteria:

- [ ] 1. Style plain text to be more readable (larger text size, line spacing, shorter paragraph width or original paragraph width)
- [ ] 2. Move zoom in and zoom out buttons to the right of the zoom percentage indicator
- [ ] 3. Change control of scroll to scroll only the entire page and not to zoom the image if the cursor is within the page image viewer area
- [ ] 4. Download options are for: Image, Plain Text, PDF and Download Issue PDF

**Comment by respinos** [comment]
re: 3 --- I don't recall ColinF mentioning compass navigation buttons. Where did this come from?

**Comment by bnhowell** [comment]
I thought he did mention it but I could be misremembering things. I'll remove it for now.

**Comment by kaylaondracek** [comment]
Closing this story - added unique ACs to #140
