### ISSUE TITLE
Help Page UX & accessibility improvements

### ISSUE THREAD

**Issue by bnhowell** [mlibrary/fishrappr#135]
## Description: 

As a user I want to easily identify what help page I’m on from a left hand navigation and see a list other about/help pages (About the Michigan Daily Digital Library, How to Search, Contact Us) so I can find the resources I need

## Acceptance Criteria:

- [x] 1. Style the left hand navigation for help pages as a white box with grey rounded border like 'narrow results' widget in search results page
- [x] 2. Style help pages left hand navigation with header titled 'Help' with indented pages 'How to Search' and 'Contact Us' and a second header 'About' with indented page 'About Fishrappr'. All this text would be dark grey text and underlined text when identifying the current page
- [x] 3. Place footer (same as home page) in help pages
- [x] 4. Background color of help pages can be lighter (Hex: F8F8F8) to align more with blacklight interface

**Comment by gordonleacock** [comment]
I believe this is done now.
