### ISSUE TITLE
Default "page of the day" functionality

### ISSUE THREAD

**Issue by kaylaondracek** [mlibrary/fishrappr#138]
## Description: 
As a user, I want to be able to view the front pages of issues that were published "on this day" in previous years so that I have an alternative starting point for potential research and exploration.

Please note that wireframes do not reflect results of backlog refinement discussion 6/30

When front page is clicked the user will go to image viewer front page.

When browse is selected, user will go to browse page for that month/day.

Additional functionality such as randomization closer to the day's date is upcoming.

## Acceptance Criteria:

- [x] "Page of the day" should display on front page of the application and be positioned as in the wireframes: https://projects.invisionapp.com/share/VS73TWYC2#/screens/166948410.
- [x] The feature should display the front page of a random assortment of days throughout the run of the Michigan Daily
- [x] The feature should show 3 days
- [ ] ~~Thumbnails should be slightly larger than what displays for search results (what are dimensions?)~~
- [x] Each entry should show appropriate metadata for that issue

**Comment by gordonleacock** [comment]
I was going to get started on this before my vacation but Roger strong recommended working more on issue #137 instead. So I will tackle this in our next Sprint (#9).

**Comment by respinos** [comment]
- What size for the thumbnails? The default we're using is 200px wide, and the invision document is 215px wide.

- Right now: it will pick a random 3 days from today's date and if there are no results (e.g. when you're using The Michigan Daily) just 3 random days

**Comment by grepcats** [comment]
Per @Treevore, 200px is a-ok!

**Comment by kaylaondracek** [comment]
Oops, I was signed in under my other github account!
