### ISSUE TITLE
Include additional metadata and information in Issue OCR download README file

### ISSUE THREAD

**Issue by kaylaondracek** [mlibrary/fishrappr#154]
## Description: 
From ticket #142 :  Included in this zip archive is a README file that contains metadata for that issue: "The Michigan Daily" [or relevant title], Vol, Iss, Date. 
To Do - review above info to determine relevancy. Is it necessary to include "The Michigan Daily" as well as edition title (summer issues have different title), and can we pull this metadata out easily? Do we need to include language about HT in this README file?

//Will have a meeting with HT (Sandra & Ange) on 7/28 and will ask if HT language is needed or expected in a README file.

UPDATE
Given that we are no longer relying on HT to serve images to fishrappr, it's not necessary to include links to content in HathiTrust. Metadata for README file should mimic that for the PDF cover page:
The Michigan Daily
Secondary Title, Date, vol. #, iss. #.

An example would be:
The Michigan Daily
U. of M. Daily, 1893-09-03 (vol. 4, iss. 1)

Rights statement information forthcoming.

## Acceptance Criteria:

- [x] Metadata should include secondary title, date of issue, volume number, and issue number as described above

**Comment by respinos** [comment]
Matching the PDF + table of contents:

```
Michigan Daily
October 26, 1956
(vol. 67, iss. 33, ed. 1)

8 pages
- 1: mdp.39015071756402-00000301.txt
- 2: mdp.39015071756402-00000302.txt
- 3: mdp.39015071756402-00000303.txt
- 4: mdp.39015071756402-00000304.txt
- 5: mdp.39015071756402-00000305.txt
- 6: mdp.39015071756402-00000306.txt
- 7: mdp.39015071756402-00000307.txt
- 8: mdp.39015071756402-00000308.txt

The Michigan Daily
http://michigandaily.org

Curabitur vestibulum faucibus mauris ac auctor. Sed consectetur libero vel finibus interdum. Donec et lectus pulvinar, convallis ligula vel, hendrerit purus. Sed id velit nec orci ultricies fringilla. Fusce ac pellentesque ligula. Cras tempor diam dolor, vitae lacinia ipsum convallis non. Pellentesque pharetra semper ex tincidunt eleifend.
```
