### ISSUE TITLE
Review document outlines

### ISSUE THREAD

**Issue by respinos** [mlibrary/fishrappr#162]
## Description: 

Document outlines are inconsistent across pages: blacklight pages have `<h1>Fishrappr</h1>`, home page and page view don't emit a leading header at all.

## Acceptance Criteria:

- [x] A. `<h1>` should be consistent within context: it should at least match the publication, for now (may end up following searchworks style)
- [x] B. for consistency, home page outline should allow for featured items to be `<h3>` as they are in search results
- [ ] C. page view should fill out its outline (has missing `<h3>`
- [x] D. remove headers where there are more appropriate tags

**Comment by gordonleacock** [comment]
Status:
Home page done.

**Comment by gordonleacock** [comment]
- On catalog page search results are now inside <article> tags per Colin F, kudos to roger for helping me with this.
- On catalog page facet headers are now buttons per Colin F.
- On catalog page face **X** remove buttons for links describe what they are removing per Colin F.
- On catalog page for facet counts adds attr title of "Number of records". If this isn't optimal (shows as a tooltip) I can working on figuring out how to using some sr-only text instead.

**Comment by gordonleacock** [comment]
Cleaned up document outlines for Browse, Help, and Catalog pages.
Browse page thumbnails should probably use `<figure>` and `<figurecaption>` but that took me deeper into the guts of blacklight than seemed good. Will Discuss with Roger.
A problem with some the Help pages cropped up with this code:

>     <div class="container">
>       <h1 class="sr-only application-heading">Fishrappr</h1>
> 
>       <div class="row">
>   <div class="col-md-12">
>     <div id="main-flashes">
>       <div class="flash_messages">
> </div>
> 
>     </div>
>   </div>
> </div>
> 
> 
>       <div class="row">
>         
> <div class="row"</div>
>   <div class="col-md-4">
>     <h1 class="sr-only">Help Pages</h1>
