### ISSUE TITLE
Modifications to browse page

### ISSUE THREAD

**Issue by kaylaondracek** [mlibrary/fishrappr#168]
## Description: 
Modifications to browse page

## Acceptance Criteria:

- [x] When one clicks an issue and goes to the image viewer page, that page has links "Back to Results" and "Start Over" which both go to the catalog index view, not back to the browse page. Covered in issue #165.
- [x] Decade drop down options show "1960" instead of "1960s", etc..
- [x] Improve labeling or description so it is clear we are browsing issues not pages.

**Comment by gordonleacock** [comment]
Done

**Comment by kaylaondracek** [comment]
Some issues with the issue navigation bar not appearing and then appearing strangely - Gordon will look into it.

**Comment by kaylaondracek** [comment]
Hi Gordon - can you confirm this was fixed? It looks like it was, but I wanted to check with you.

**Comment by gordonleacock** [comment]
No fixed but I can't reproduce. Roger and I need to talk about a code
change that might resolve this.

**Comment by gordonleacock** [comment]
Also, by standup agreement we removed the start over links (one for the catalog and one to return to browse) from the show (image viewer) page.
