### ISSUE TITLE
Keep search results when opening a page to view (User Story #33)

### ISSUE THREAD

**Issue by gordonleacock** [mlibrary/fishrappr#17]
Description: 
Go "back to [search] results" during research 

Acceptance Criteria:

- [x] I can always "go back" to see my last search results
- [x] I don't lose my place when viewing a page ("they don't lose their place")

**Comment by kaylaondracek** [comment]
Is the team ok with changing the ACs to the below? Also, please confirm whether AC 3 should be an additional user story or whether it's ok to have them all together (if these can be all done in 1 sprint, in other words). I think the rewording helps make expectations a little more explicit.
1. Once the user is on a page image they navigated to from "search results", they can view a link that says "return to search results"
2. Clicking the link brings the user back to the originating search
[3]. If the user pages through the issue from the initial page image, they will still be able to see a link that says "return to search results" and the link will function as above.

**Comment by gordonleacock** [comment]
Yes, the "return to search results" should take them back to the search
page showing it as they left it (Principle of Least Surprise)
