### ISSUE TITLE
Remove search results view options and per page options

### ISSUE THREAD

**Issue by kaylaondracek** [mlibrary/fishrappr#180]
## Description: 

These are not needed and can be removed.

Default number results per page is 50.

## Acceptance Criteria:

- [x] Buttons and number options are removed
- [x] Default number results per page is 50.

**Comment by kaylaondracek** [comment]
Looks like the first AC was completed but default results per page is currently 24 rather than 50

**Comment by gordonleacock** [comment]
Roger update the per page count to 50.

**Comment by gordonleacock** [comment]
I believe this issue is ready to close.
