### ISSUE TITLE
Staging: Browse shows incorrect metadata with images

### ISSUE THREAD

**Issue by kaylaondracek** [mlibrary/fishrappr#192]
## Description: 
(probably a data issue - not calculating correct sequence) 

When selecting a single day in browse, the display shows multiple issues with the same metadata that does not reflect the actual image number.

Steps to replicate:

- Navigate to staging: https://fishrappr-bhl-staging.hydra.lib.umich.edu
- Navigate to Browse
- Select "September" for Month; select "13" for day. Select "Browse" button
- Observe 8 "issues" for September 13, 1969 and 20 "issues" for September 13, 1985, all with "Image 1" metadata but not the first page.

This may be happening with all images (observe default browse).

See screenshot attached
![screen shot 2016-09-13 at 9 17 40 am](https://cloud.githubusercontent.com/assets/14596911/18475043/f04d1644-7992-11e6-876f-3b36aca0a40e.png)

**Comment by respinos** [comment]
Confusion from new `issue_sequence` field on pages conflicting with tracking the *issue's sequence*. Fixed.
