### ISSUE TITLE
Identify tabloid pages and include text about how to navigate tabloid pages in viewer

### ISSUE THREAD

**Issue by kaylaondracek** [mlibrary/fishrappr#199]
## Description:

As a user, I would like to see information about how to properly navigate and understand tabloid pages in the michigan daily.
## Acceptance Criteria:
- [x] Include tabloid information from tsv into METS
- [x] Change XML importer to include this info
- [x] For pages that have this element, include initial helper text on image viewer; add an `id` of `tabloid-pages` to this section header
- [x] Link initial helper text to this section

**Comment by respinos** [comment]
![image](https://cloud.githubusercontent.com/assets/537867/19163722/207aa152-8bcb-11e6-850b-c7fc46cec1b9.png)
