### ISSUE TITLE
Catalog page search form should match filter options as closely as possible; hide date options at top when date facet is selected

### ISSUE THREAD

**Issue by kaylaondracek** [mlibrary/fishrappr#201]
## Description: 
As a user, I need consistent interactions with the search options.

Catalog page search form should match filter options as closely as possible; hide date options at top when date facet is selected

## Acceptance Criteria:

- [x] Hide the date options in the search box whenever any date facet is selected
- [ ]

**Comment by gordonleacock** [comment]
Okay, I worked on this issue today. Am I correct in thinking that any I should keep my hands (code) off any date search parameters used prior to a date facet being selected. In other words, if a user starts a search looking for students in 1969, I won't disable the part of the search for 1969.

**Comment by kaylaondracek** [comment]
Hi Gordon - yes, I think that's right. It should only disabled once the user starts fiddling with the facet.
