### ISSUE TITLE
No "Back to Top" button in the page view page. 

### ISSUE THREAD

**Issue by bnhowell** [mlibrary/fishrappr#212]
## Description: 
There is no "Back to Top" button in the page view page. 

## Acceptance Criteria:

- [x] Implement "Back to Top" button in page view page

**Comment by gordonleacock** [comment]
I've never seen a design document with this feature so I'm relabelling this as an "enhancement."

**Comment by bnhowell** [comment]
@gordonleacock. I thought we would have the same 'Back to Top"button as in the search results page: 

Like in the lower right corner of this screenshot:
![screen shot 2016-09-26 at 4 54 33 pm](https://cloud.githubusercontent.com/assets/16804543/18851450/0d48db12-840a-11e6-965c-d0a57efe7d43.png)

**Comment by gordonleacock** [comment]
That’s fine Ben. I just didn’t think the “bug” label was correct.

**Comment by gordonleacock** [comment]
Done.
