### ISSUE TITLE
Home page copy not wrapping correctly in mobile

### ISSUE THREAD

**Issue by bnhowell** [mlibrary/fishrappr#213]
## Description: 
On the home page, the MiDaily Description copy: "Student News at the University of Michigan 130,000 papers covering over 120 of campus life" is not wrapping correctly on mobile. 

## Acceptance Criteria:

- [x] Make header text responsive ("Bentley Historical Library University of Michigan")
- [x] Make descriptive text responsive ("Student News at the University of Michigan 130,000 papers...")

**Comment by gordonleacock** [comment]
Header text is not text, it is an image.
