### ISSUE TITLE
Home Page Search box UI improvement

### ISSUE THREAD

**Issue by bnhowell** [mlibrary/fishrappr#215]
## Description: 

UI improvements on the home page search box to the following element:  <SPAN> .between-to

## Acceptance Criteria:

- [x] resize text size of 'to' from 35px to 16px

![screen shot 2016-09-20 at 3 31 33 pm](https://cloud.githubusercontent.com/assets/16804543/18685854/c9d80fd6-7f47-11e6-83ba-474452f72911.png)

- [x] Make search box on home and catalog pages responsive.

**Comment by gordonleacock** [comment]
Okay, I'm folding search box redesign (make it like a sentence) into this issue.

**Comment by gordonleacock** [comment]
Done.
