### ISSUE TITLE
Page layout of page viewer

### ISSUE THREAD

**Issue by bnhowell** [mlibrary/fishrappr#216]
## Description: 
Currently in mobile, the download options and permalink wrap to the bottom of the screen. The download options would be more discoverable if they were below the image viewer.
It would be preferable to have these options below the image and above the OCR text section. 

## Acceptance Criteria:

- [x] Place OCR text below the download and permalink options in mobile

**Comment by respinos** [comment]
![image](https://cloud.githubusercontent.com/assets/537867/19162631/a4885386-8bc6-11e6-8444-bb17f21971ff.png)

We could have the default document order be `[ buttons | fulltext ]`, which lets them be full-width for mobile. These are re-ordered to `[ fulltext | buttons ]` for desktop. Which maybe helps with where the keyboard tabbing takes you?
