### ISSUE TITLE
Configure publication as "Michigan Daily Digital Archive"

### ISSUE THREAD

**Issue by respinos** [mlibrary/fishrappr#220]
## Acceptance Criteria:

- [x] publication name should be "The MIchigan Daily Digital Archives"
- [x] Change date to “1890 - Present”
- [x] The descriptive text in the header can be: “The student newspaper at the University of Michigan”  and “125 years of editorial freedom.”
- [x] Revise random feature heading: “This date in the Michigan Daily”

**Comment by gordonleacock** [comment]
Done.

**Comment by gordonleacock** [comment]
@respinos, @njaffer  - I didn't mess with the publication tag in the menu bar.
