### ISSUE TITLE
Update donor information

### ISSUE THREAD

**Issue by respinos** [mlibrary/fishrappr#221]
## Acceptance Criteria:

- [x] New Header - “Thank You to the Kemp Family Foundation”
- [x] Descriptive text stays the same except for, “...financial support of our donor.”
- [x] Link to page about donor

**Comment by gordonleacock** [comment]
Please see issues #213 and #220 too.

**Comment by gordonleacock** [comment]
@bnhowell - I think I got the link text correct, please check.
