### ISSUE TITLE
Gather content for About the Digital Archives page

### ISSUE THREAD

**Issue by njaffer** [mlibrary/fishrappr#23]
### Description:

To view an "about" page for the application/site
### Acceptance Criteria:
- [ ] The information for About Us page is documented

**Comment by kaylaondracek** [comment]
Mike has been speaking with the BHL Directory of Communications Lara Zielin to start putting together this language. She will be OOO until 5/25 so we are going to make this a sprint 4 goal.

**Comment by kaylaondracek** [comment]
Lara Zielin let me/Mike know that Terry will be drafting the final text on the About page. He has the source text that we've developed so far. I'm going to ask that he has this completed by the end of August - hopefully we are closer to having any copyright issues figured out by then, in case those impact what is included in the About page.

**Comment by kaylaondracek** [comment]
Lara is going to get an update on this for me by the 23rd and have a time-frame for completion then (as of 8/16/2016)

**Comment by kaylaondracek** [comment]
Terry will have the about page with donor information ready for us by October 1st.
