### ISSUE TITLE
Gather content for Help page

### ISSUE THREAD

**Issue by njaffer** [mlibrary/fishrappr#24]
## Description: 

Create Help page

## Acceptance Criteria:

- [x] The information for Help page is gathered in a document

**Comment by kaylaondracek** [comment]
This story and [issue 9](https://github.com/mlibrary/fishrappr/issues/9) are both marked as research track. Should one be research track & one be for actual creation and implementation of the page?

**Comment by njaffer** [comment]
Right, I removed the label 'Research Track' from #9

Thanks!

**Comment by kaylaondracek** [comment]
I have created a shared Google doc for the FAQ page with the basic page structure recommended by UX. Nothing populated yet.

**Comment by kaylaondracek** [comment]
Incorporate latest feedback into help page for Sprint 10

**Comment by bnhowell** [comment]
Here is a final draft for the Help Pages: 
1. How to Search [Google Doc]
(https://docs.google.com/document/d/19Gg5jMXwxmUJmG7bPEP0_hPsjLkdeDIcrYz89wPLGRM/edit#heading=h.2wuoeii5pkef)
2. Image Viewer, Plain Text & Download Help (or whatever we decide to call this page) [Google Doc]
(https://docs.google.com/document/d/19Gg5jMXwxmUJmG7bPEP0_hPsjLkdeDIcrYz89wPLGRM/edit#heading=h.2wuoeii5pkef)

I'd love feedback @njaffer and @sooty on content within these documents before mocking up final designs.

**Comment by njaffer** [comment]
The document looks good. Thanks @bnhowell

**Comment by gordonleacock** [comment]
I think this one is ready to close too.
