### ISSUE TITLE
Add "Search First Page Only" option

### ISSUE THREAD

**Issue by respinos** [mlibrary/fishrappr#264]
## Description:
- add "Search First Page Only" option between "current search" summary and results graph

This should just be having a checkbox with the name `issue_sequence` with a value of `1` when checked, and then submitting the form.
## Acceptance Criteria:
- [ ] user submits a search, and can then check the box to further filter the query

**Comment by Treevore** [comment]
![screen shot 2016-10-27 at 3 27 00 pm](https://cloud.githubusercontent.com/assets/502199/19781985/db5777b8-9c59-11e6-9117-637cfdd9cf65.png)

Updated mockups, should be in zeplin shortly.

**Comment by gordonleacock** [comment]
[](![frontpageonlybutton](https://cloud.githubusercontent.com/assets/12927191/20076340/11bbc99e-a506-11e6-8fbd-c2c9252034f4.png))
