### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by respinos** [mlibrary/fishrappr#269]
## Description: 

Configure N Google Analytics profiles; application should include the tracking code if present.

## Acceptance Criteria:

- [x] page requests are logged
- [x] page events are logged (downloads, viewer interactions, etc)

**Comment by gordonleacock** [comment]
Roger - am I right in thinking that the Bentley (Mike) is going to set up a new google analytics profile for us to use when we add the Analytics javascript?

**Comment by respinos** [comment]
We're going to log to multiple profiles (which of course could change at some point...)

**Comment by respinos** [comment]
`google-analytics-rails` exposes a `ga` object to global javascript context.

We can use that to track events-as-pageviews by binding on the `click` event

```javascript
  $("a[data-track]").on('click', function(e) {
    var $this = $(this);
    var options = {};
    options.location = $this.attr('href');
    options.title = $this.text();
    ga('send', 'pageview', options);
  })
```

Possibly the title should include the page title (`$("title").text()`).

...so we can track the downloads, mostly.

- [ ] add `data-track="true"` to the appropriate links in `app/views/catalog/_show_sidebar.html.erb` (**excluding _Download Current View_**)
- [ ] observe events in web console
- [ ] figure out how to track current view downloads
