### ISSUE TITLE
Update Using the Viewer Help

### ISSUE THREAD

**Issue by respinos** [mlibrary/fishrappr#273]
## Description: 

Update viewer help to reflect latest changes to viewer.

## Acceptance Criteria:

- [x] Take out screenshot reference from viewer help
- [x] References to pan should be removed
- [x] Add help content for  reset viewer button
- [x] *OCR and Plain Text* heading needs an `id` so it can be addressable via a fragment identifier (`ocr-and-plain-text`)

**Comment by gordonleacock** [comment]
Okay, I could make this up but I think it would be better if @bnhowell/@heidisb wrote it. Then I'll change the page. :-)

**Comment by heidisb** [comment]
I gave @bnhowell feedback on all the copy he drafted last month, but haven't looked at it since or seen it in production. I will leave this to him unless he pings me for a once over.

**Comment by bnhowell** [comment]
I uploaded the wireframe for the help page in Zeplin. Good to go.

**Comment by respinos** [comment]
I updated the view file with `ocr-and-plain-text`. This'll need to be re-added with syncing from zeplin.
