### ISSUE TITLE
Address accessibility audit

### ISSUE THREAD

**Issue by respinos** [mlibrary/fishrappr#275]
## Description: 

See: https://docs.google.com/a/umich.edu/document/d/1UgMh1GiL3Y2zaAZxs-DGnrPxnijrwfFMGO5Di8aYHlQ/edit?usp=drive_web

### Search

- [x] a. search label and input[name=q] should be linked
- [x] b. search result headings should appear as obvious links (color, underline)
- [x] c. “Results frequency by decade” data are not displayed with keyboard-only. Can we add an on-focus and on-blur to the on-hover to trigger the event? It does work well with NVDA and VoiceOver. 

### Image Viewer

- [x] d. Perhaps announce to users that they can use the arrow keys to pan the text, in addition to using the mouse. Very cool that you can do this, but the image must have keyboard focus and there is no visual indication of this. 

### Browse

- [x] e. Add labels to form elements in search.

### General

- [x] f. Thumbnails of MD pages do not have alt text.

**Comment by gordonleacock** [comment]
For c. I thought he was talking about the heading itself, not the data in the graph, which is highlit on tab.

For e. was he talking about screen-reader label (which we have) or visible label (where we only have a few)?

What are "MD" pages?

**Comment by respinos** [comment]
"MD" == "Michigan Daily"

c: no, he's talking about it'd be nice if when you tab onto "1920s" the information text would appear as when you hover over "1920s".

e: the browse form has one label, not connected by id to any control; none of the selects have a corresponding label. The labels can be sr-only.

**Comment by respinos** [comment]
f: alt text is like "image of February 28, 1957 - number 1"

c: labels added to all select statements.

**Comment by gordonleacock** [comment]
@roger: Re item f: I'm seeing the old text, alt="Thumbnail of Daily page" did you comment on f mean you want me to add it?

**Comment by respinos** [comment]
The fix may be in the embiggen branch. You can ignore this.
