### ISSUE TITLE
Use Page Numbers when available

### ISSUE THREAD

**Issue by respinos** [mlibrary/fishrappr#278]
## Description: 

When available, present page numbers.

## Acceptance Criteria:

- [ ] Page N
- [ ] Page NB: e.g. the second occurrence of *Page N* in this issue)
- [ ] Page (S): e.g. no page number available; *S* is the sequence of this page in the issue

e.g.

> The Michigan Daily > December 12, 1979 (vol. 90, iss. 80) > Page 5
> The Michigan Daily > December 12, 1979 (vol. 90, iss. 80) > Page 5B
> The Michigan Daily > December 12, 1979 (vol. 90, iss. 80) > Page (10)

**Comment by bnhowell** [comment]
I recommend using 'Page Image N' regardless of whether page number is technically available or not.

**Comment by respinos** [comment]
Going with *Page Image S*.
