### ISSUE TITLE
Feedback Fixes

### ISSUE THREAD

**Issue by respinos** [mlibrary/fishrappr#282]
## Description: 

Hi - I found some things while looking through the static content on the site. For your consideration: 

## Acceptance Criteria:

- [x] On most of the static content pages, the font size appears to be 16 px and the line height is 24 px. However, on the Kemp Foundation page and the Contact Us page, the font size is 20 px and line height is 32 px. Was this deliberate?
- [x] There is a typo on the About page. In the Technologies section, second sentence, says "...was chosen as the starting point for the project due to it support..." Should be "due to its support".
- [x] On the Rights Statement page, it's the only place where Michigan Daily is italicized. Should probably be consistent throughout the site (?).
- [x] On the Contact Us page, there's a typo. Should be feedback not feeback. 
- [x] On How to Search page, should Wildcard Search be #333333 like the other subheads, or is it correct that it's #6e6e6e? Looks like it should be the same as Boolean Search (which looks like #333333).
- [x] On Using the Page Viewer page, should subhead Page viewer tools be Page Viewer Tools to be consistent with the rest of the subheads on the page?
- [x] ...fix h2 > h4

**Comment by Treevore** [comment]
The 24px font size was meant to be used as a larger introductory sized paragraph for each page. If there is a body of text under the first header it should be 24px.

"Wildcard Search",  "Boolean Search" can be changed to #333333 and a font size of 20px
This can also be applied to "Pages" & "Issues" at the bottom of the "Using the Page View" section. The original idea was to provide a subheading for that section, but it might be easier to show that through a text size change vs a lighter grey.
