### ISSUE TITLE
Populate decade/year values from available data

### ISSUE THREAD

**Issue by respinos** [mlibrary/fishrappr#286]
## Description: 

Select lists (in browse, possibly other places) have date information from the future (e.g. 2016).

## Acceptance Criteria:

- [x] decades and year will reflect currently ingested/indexed data

**Comment by respinos** [comment]
I'd vote for pulling this information from the database (query to follow).

**Comment by gordonleacock** [comment]
So I didn't add this to the graph or facet code between it is obvious in those places that there is no data after 2014. But this is done for the browse page.

**Comment by respinos** [comment]
Right --- those are based on a query, so they're okay.

What about the search form selects? Ah --- they're okay because it's just a text field. Never mind.
