### ISSUE TITLE
Add Script to parse XML MiDaily data and put it into the rails DB

### ISSUE THREAD

**Issue by gordonleacock** [mlibrary/fishrappr#29]
### Description: 
Add Script to parse XML MiDaily data and put it into the rails DB

This stand alone script:
-- finds and parses the XML files and 
-- adds the gathered data info the issues and pages sqlite3 db tables via active record calls

**Background**: Chris is getting tag data files that describe the scanned Daily pages. She has an initial method for converting those into mostly standard XML data files.

### Acceptance Criteria:

[ ] add a new rake task to do this work
[ ] add xml_data folder in the tmp directory to hold xml data files
[ ] add an xml_to_db rake task that will parse each xml file and add it's data to the issues and pages tables via active record

**Comment by respinos** [comment]
Why is the databased named in the script and not using whatever is configured in RAILS_ENV?

**Comment by gordonleacock** [comment]
Done.

**Comment by gordonleacock** [comment]
All done. If we need significant modification we are re-open this issue or create a new one.
