### ISSUE TITLE
Implement Grid View for search results

### ISSUE THREAD

**Issue by njaffer** [mlibrary/fishrappr#43]
## Description: 

Implement Grid View for search results

## Acceptance Criteria:

- [x] The user can see the search results in a grid

**Comment by kaylaondracek** [comment]
Trevor is looking into appropriate sizing for grid view thumbnails

**Comment by respinos** [comment]
blacklight-gallery assumes openseadragon for viewing images (even though it's not used in the gallery themselves). Researching what it actually adds vs. what would have to be overridden (e.g. how https://github.com/sul-dlss/SearchWorks/ uses blacklight-gallery and then modifies that use)

**Comment by njaffer** [comment]
@respinos implemented the solution without blacklight gallery gem!
