### ISSUE TITLE
Perceive highlighted keyword search term for screen reader on OCR

### ISSUE THREAD

**Issue by njaffer** [mlibrary/fishrappr#45]
## Description: 
As a user, I need to perceive highlighted keyword search term for screen reader on OCR so that all users can understand where keywords appear in the newspaper text.

## Acceptance Criteria:
- [ ] 1. See what users expect during user testing - gather that feedback
- [ ] 2. Screen reader users can perceive highlighted hits within search results article snippet 
- [ ] 3. Screen reader users perceive when multiple keywords are present in search results. 

ACs by Ben.

**Comment by kaylaondracek** [comment]
Ben & Roger are going to work together on this.

**Comment by respinos** [comment]
ColinF suggested marking up highlights with `<em>` and overriding the default styles, but is looking at whether there's any more appropriate HTML5 arcana.
