### ISSUE TITLE
Implement Contact Form page

### ISSUE THREAD

**Issue by njaffer** [mlibrary/fishrappr#46]
## Acceptance Criteria:
Form should include:
- [x] 1. "Your name (Required)" - text field
- [x] 2. "Your email address (Required)" - text field
- [x] 2.a. Field contents should be formed as an email address, eg aaa@aaaa.aaa
- [x] 3. "What do you need help with?"
- [x] 3.a. Selectable list: Searching, Problem with content or metadata, Technical support, General comment or concern, Other
- [x] 4. "Your message (Required)" - text field
- [x] 5. "Submit" button
- [x] 5.a. "Submit" button should send an email to bhl-digital-support@umich.edu (new group for this purpose - just has Kayla & Mike on it so far)
- [x] Wireframe https://projects.invisionapp.com/share/VS73TWYC2#/screens/154098798
- [x] Page heading, Title, labels is pulled from YAML file

**Comment by gordonleacock** [comment]
Still to come:

1. Hover highlighting cues for input boxes and checkmarks
2. Remove "*"s (where did those come from?)
3. Actually generate and send email
4. Align name and email in one row
5. Make tabbing work correctly
6. Accessibility improvements and testing

**Comment by gordonleacock** [comment]
Error generation when a required field is blank doesn't work yet. Ah, the joys of simple_form. 
Also tab index order for submit button doesn't work correctly. It jumps from the last input field to the "Fishrappr" link at the top of the page.
Testing email generation is going to wait on the test server.

**Comment by gordonleacock** [comment]
Ready to merge, check it out.

**For a later sprint:**

1. We can test email when we get the test server running and loaded.
2. Add autofocus for first form field (name) if UX team okays.

**Comment by kaylaondracek** [comment]
A few tweaks to be made - closing
