### ISSUE TITLE
Generating PDFs

### ISSUE THREAD

**Issue by respinos** [mlibrary/fishrappr#67]
## Description: 

Determine best approach to generating PDFs. Options:

- request PDFs from imgsrv@hathitrust
  - requires a custom client for initiating/tracking download status (easy)
  - have to track the HathiTrust _page sequence_
  - generated PDFs **would** have the typical HathiTrust colophon and watermarks
  - AltoXML would be have to be ingested into the HathiTrust repository
    - ...or imgsrv learns to process Prime XML
- build a fishrappr version of the PDF build scripts
  - images would have to be fetched from imgsrv@hathitrust
  - fishrappr would have the coordinate OCR
  - put whatever fishrappr wants in the PDF (e.g. colophon)
  - would need to reimplement much of the infrastructure/monitoring/etc.

The first option is preferable, assuming everyone can agree to the restrictions.

**Notes**: `fishrappr` is using heuristics to infer the HT sequence from page data (e.g. `IMG00000819` == `819`; so clever). Without the heuristic, `imgsrv` has to be modified to be given the fileid and then look up the other material that relate to that file (e.g. image and OCR text). Does that heuristic make sense in `imgsrv`? Perhaps doing the inference in `fishrappr` is the right thing to do? 

## Acceptance Criteria:

- [x] can generate a PDF of an entire issue
- [ ] can generate a PDF of a selection of pages in that issue
- [x] determine requirements for generating cover pages

Possible cover page options (in order of increasing complexity to implement):

- do nothing
- insert additional page to PDF, resulting in separate colophon pages for Bentley/Michigan Daily and HathiTrust
- replace the colophon page with new copy: the wrinkle is preserving/replicating the HathiTrust logo and rights statement

**Comment by respinos** [comment]
re: generating a selection of pages in the issue --- pinging @bnhowell and @Treevore about what UX this should take (the "dog-ears" that we're using in HathiTrust?)

**Comment by bnhowell** [comment]
I like HathiTrust's interactions overall. I would want the accessibility
related focus order to go: (Previous page, Select page for Download (or the
terminology we use for this 'dog-ears' feature, Next Page). When the user
selects the page a button like the HathiTrust button could appear in the
left hand 'Download Options' section and above the article for the user to
select and jump to another page (as in HathiTrust). Would this feature work
just within one issue or some other range (inserts, etc.)?



On Fri, Jul 1, 2016 at 5:36 PM, respinos <notifications@github.com> wrote:

> re: generating a selection of pages in the issue --- pinging @bnhowell
> <https://github.com/bnhowell> and @Treevore <https://github.com/Treevore>
> about what UX this should take (the "dog-ears" that we're using in
> HathiTrust?)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mlibrary/fishrappr/issues/67#issuecomment-230052540>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AQBqvz6jG8sB-fymIXSBg-C0ROLI3ouFks5qRYhGgaJpZM4Iche8>
> .
>



-- 
Ben Howell | Accessibility & User Experience Specialist
Design & Discovery | LIT | University of Michigan Library
bnhowell@gmail.com

**Comment by respinos** [comment]
> Would this feature work just within one issue...?

Yes, at least for now. Binding pages from disparate issues is intriguing, but beyond the scope of this release.

> I would want the accessibility related focus order go: Previous Page, Select Page for Download, Next Page

What about having the option be *after* the navigation? 

```
<- Previous Page [ Current Page Indicator ] Next Page -> | Select Page for Download
```

 --- your navigation movement/tabbing isn't interrupted by the select page.

**Comment by bnhowell** [comment]
I would have to ask Brandon Werner. My gut feeling is that it fits where
it's most contextual. (At the moment I feel like that's between page
selection, I very well could be wrong)

On Tue, Jul 5, 2016 at 11:49 AM, respinos <notifications@github.com> wrote:

> Would this feature work just within one issue...?
>
> Yes, at least for now. Binding pages from disparate issues is intriguing,
> but beyond the scope of this release.
>
> I would want the accessibility related focus order go: Previous Page,
> Select Page for Download, Next Page
>
> What about having the option be *after* the navigation?
>
> <- Previous Page [ Current Page Indicator ] Next Page -> | Select Page for Download
>
> --- your navigation movement/tabbing isn't interrupted by the select page.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mlibrary/fishrappr/issues/67#issuecomment-230518708>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AQBqvzUTrEoyOMHOiBXUfp99J8PYwZxUks5qSnztgaJpZM4Iche8>
> .
>



-- 
Ben Howell | Accessibility & User Experience Specialist
Design & Discovery | LIT | University of Michigan Library
bnhowell@gmail.com
