### ISSUE TITLE
Donor appreciation page creation

### ISSUE THREAD

**Issue by kaylaondracek** [mlibrary/fishrappr#74]
## Description: 
As a user, I want to be able to navigate to a "donor appreciation page" and be presented with the donor appreciation page so that I can see how the project was supported.

## Acceptance Criteria:

- [ ] 1. Wireframes developed by UX are implemented 
- [ ] 2. User can navigate to this page via structure recommended by UX
- [ ] 3. Functionality that supports population of this page will be handled in subsequent story

A note that wireframes for a donor appreciation page have not yet been developed.

**Comment by gordonleacock** [comment]
Is this different from the "About Donors" page? If not, this issue is completed.
