### ISSUE TITLE
Filter results by date range

### ISSUE THREAD

**Issue by kaylaondracek** [mlibrary/fishrappr#76]
## Description: 
As a user, I want to be able to filter results by date range with day granularity so that I can adjust and see the amount of articles within a specific date range.

This story does not include date graph implementation. That will be covered in subsequent story.

Wireframe needs to be updated to reflect conversation in backlog refinement 6/10/2016.

## Acceptance Criteria:

- [x] 1. User is able to see date range filter in an intuitive place once they have performed a search
- [x] 2. User can use filter to narrow search results
- [x] 3. For search start and end, include Month & Day drop downs (rather than single field that relies on adherence to format). Year is an open text field
- [x] 3.a. Validation: year should be ####
- [x] 3.b. If user selects date that doesn't exist via drop downs (eg 2/31/2010), what is expected behavior? Error?

**Comment by gordonleacock** [comment]
Issue #76 is close to complete. Still need to fix some javascript bugs.
