### ISSUE TITLE
Year level search dates on home screen

### ISSUE THREAD

**Issue by kaylaondracek** [mlibrary/fishrappr#79]
## Description: 
As a user, I want to be able to start a search on the home screen and enter year-level dates as a first pass so that I can optionally restrict my search to a particular time period

## Acceptance Criteria:

- [x] 1. User can enter a start date and an end date (year only) into fields on the home page
- [x] 2. When executed, the search will bring the user to the search results page and the results will reflect the entered dates

**Comment by njaffer** [comment]
The date drop down box is populated from the indexed data.
