### ISSUE TITLE
Implement hit highlighting on page result

### ISSUE THREAD

**Issue by kaylaondracek** [mlibrary/fishrappr#90]
## Description: 
As a user, I want to see the hit highlighted keyword on the page image result so that I can see where the keyword is within the page image.

## Acceptance Criteria:

- [x] 1. The keyword results are highlighted on the page image after the user selects a search result thumbnail and is taken to the individual page image 
- [x] 2. All hits should be highlighted in orange (Ben is going to get a hex number to Roger)

**Comment by respinos** [comment]
We need an orange that works well as a transparency against the yellow-ish hue of the page image.
