### ISSUE TITLE
Search indicator icon

### ISSUE THREAD

**Issue by kaylaondracek** [mlibrary/fishrappr#92]
## Description: 
As a user, I want to be able to see an indication that my search is running so that I have visual feedback on my search and don't just see a blank screen.

Ben & Trevor will provide an icon.

## Acceptance Criteria:

- [x] 1. User can see an icon that indicates that a search is running

**Comment by gordonleacock** [comment]
I've just put in a pull request for an interim solution - it is a start. Doesn't disable the form yet.

**Comment by gordonleacock** [comment]
![screen shot 2016-06-08 at 3 23 10 pm](https://cloud.githubusercontent.com/assets/12927191/15907961/41910f1c-2d8d-11e6-9171-e7057b4d45b9.png)

**Comment by kaylaondracek** [comment]
Removed the AC requiring the form is disabled. We will wait for this piece of the feature until it proves necessary. Interim solution (shown above) was determined to be acceptable for this story via backlog refinement meeting 6/10/2016.
