### ISSUE TITLE
Display number of term hits per result entry on results page

### ISSUE THREAD

**Issue by kaylaondracek** [mlibrary/fishrappr#93]
## Description: 
As a user, I want to perceive that individual page results have indication of number of term hits on that page so that I can understand how frequent my term appears in that search result snippet.

## Acceptance Criteria:

- [ ]  1. The number of term hits that appear on each page appears in search results for grid view
- [ ]  2. The number of term hits that appear on each page appears in search results for list view

**Comment by njaffer** [comment]
There is no easy way to get the hit highlight search count for all the pages. Confirmed it with @respinos and @billdueber, and they both agreed that it is not doable
