### ISSUE TITLE
CSS cleanup

### ISSUE THREAD

**Issue by kaylaondracek** [mlibrary/fishrappr#95]
## Description: 
Cleanup of CSS styling per discussion during Sprint 3 review **[some of these aren't CSS - will update later after talking with Gordon]**

HOME PAGE
- [x] Make search field on home screen longer
- [x] Get available years from solr; should not be hard coded
- [x] Blank q doesn’t search when sent to home page - may related to available years
- [x] Convert from simple-form to plain rails form then update Nabeela's related search code
- [x] Fix dash appearance
- [x] Fix gray band above donor section
- [x] Fix wording spelling “suport"

CONTACT PAGE (and about help group of pages)
- [x] Use simple-form config ala RDR config
- [x] Suppress search bar display
- [x] When email is working change email “to” address
- [x] Add permissions request to a second email address
- [x] See if we can make email errors more specific

- [x] Fix form elements to align left
- [x] Make name and email align vertically
- [x] Separate help and about pages

## Acceptance Criteria:

- [x] Complete Home page tweaks
- [x] Complete Contact page tweaks

**Comment by gordonleacock** [comment]
Status 6-8-16:
For contact page, didn't go the full RDR route for styling.
Contact page, don't have second email address working.
Contact page, wasn't able to fix email errors but see the added placeholder.

**Comment by respinos** [comment]
Why didn't we use the RDR config for required attributes?

https://github.com/mlibrary/umrdr/blob/master/config/initializers/simple_form.rb#L7

-R

**Comment by gordonleacock** [comment]
We can. I saw a simple and quick solution with scss and used that. I'll add
this to the next iteration.

**Comment by gordonleacock** [comment]
Waiting on email testing on staging server. Also, changing email errors is not done and difficult to track down; I'm hoping with the other changes (placeholders, etc.) that we won't find it necessary.

**Comment by gordonleacock** [comment]
This issue is done.
