### ISSUE TITLE
Update contact form to include "request permission" request type and Daily's email

### ISSUE THREAD

**Issue by kaylaondracek** [mlibrary/fishrappr#96]
## Description: 
As a user, I want to be able to request permission to use content from the Michigan Daily so that I can determine my ability to use of content beyond what is acceptable in fair use

Note that PO will talk to Mark about using a group email instead of his particular email address, but shouldn't impact implementation for now.

## Acceptance Criteria:

- [x] 1. To contact page, an entry for ""request permission assistance"" is added to the options
- [x] 2. When this is selected, the email is directed to Mark Bealafeld instead of BHL (mbealafe@umich.edu)

**Comment by njaffer** [comment]
To Do[ Sprint 5]: Add code for proper message  headers

**Comment by gordonleacock** [comment]
Added headers but not production addresses yet because we need to test first on nectar!

**Comment by gordonleacock** [comment]
Completed now.
